### PR TITLE
Remove inner borders

### PR DESCRIPTION
**Pull request by CodeGreen0386**
I got it to work in a pretty janky way, but relatively clean all things considered:
I removed the border graphics from the table style, and created a frame style using graphics made from the table borders.
Then I added a frame with that style around the tables.
Now it *looks* like the tables have no inner borders, since the frame borders encompass the table.

### CODE REVIEW

**Comment by heinwessels** [comment]
Thanks for the effort CodeGreen! Howeer, it seems it's still not quite as in vanilla. You removed the horizontal border-lines, but this also removed the vertical border lines which do exist in vanilla. Do you think you would be able to achieve "full-vanilla" with your hack?

---
**Vanilla**
image

**After your changes**
image

**Before your changes (for completeness)**
image

**Comment by CodeGreen0386** [comment]
Ooh, somehow I missed that. Let me see what I can do.

**Comment by CodeGreen0386** [comment]
Okay, it's a little more jank than before, basically to the extent of what I originally thought it would be, but I got it to work.

**Comment by heinwessels** [comment]
That looks perfect. Thanks!

image

**Pull request merged**
